# The Platinum Searcher
[[tool]]
name = 'pt'
symbol = 'Pt'

[tool.description]
fullname = 'The Platinum Searcher'
url = 'https://github.com/monochromegane/the_platinum_searcher'

[tool.opt]
short = '-'
full = '--'
combine = false
# opt.grepformat = ''

[tool.opt.set]
base = ['--nocolor', '--nogroup']
search = []
filelist = ['--files-with-matches']

# [tool.opt.variant]

[tool.opt.variant.case]
ignore = ['--ignore-case']
smart = ['--smart-case']

[tool.opt.variant.word]
pattern = []
regex = ['-e']

[tool.opt.variant.target]
hidden = ['--hidden']
notvcs = ['--skip-vcs-ignores']

# The Silver Searcher
[[tool]]
name = 'ag'
symbol = 'Ag'

[tool.description]
fullname = 'The Silver Searcher'
url = 'https://github.com/ggreer/the_silver_searcher'

[tool.opt]
short = '-'
full = '--'
combine = false
# opt.grepformat = ''

[tool.opt.set]
base = ['--nocolor', '--nogroup', '--column']
search = []
filelist = ['--files-with-matches']

# [tool.opt.variant]

[tool.opt.variant.case]
ignore = ['--ignore-case']
smart = ['--smart-case']

[tool.opt.variant.word]
pattern = ['--literal']
regex = []

[tool.opt.variant.target]
hidden = ['--hidden']
notvcs = ['--skip-vcs-ignores']
